### PR TITLE
Build & release using Fontship

### PR DESCRIPTION
**Pull request by alerque**
Work in progress. In order to get a release out on parity with "v2.2" (which is actually 2.210 according to the internal font versioning) I'll probably need to disable OTF builds, the hinter doesn't like most of the fonts:

```
psautohint: error: argument FONT: .fontship/LeagueMono-Extended-instance.otf is not a valid path.
```

TTF hinting seems to be okay, but the tooling irregularities make `psautohint` vs. `ttfautohint` like comparing apples to hedgehogs. I'm going to bed.

### CODE REVIEW

**Comment by alerque** [comment]
Hey @sursly do you happen to have any memory of why you added the `--keep-overlaps` argument to `fontmake` in b3e7fa6? By default Fontship doesn't use this option and I'm wondering if it matters. I don't *see* any difference, but since I don't know exactly what that was supposed to fix I'm not sure what potential problem I should be on the lookout for.

**Comment by sursly** [comment]
Sorry! I think that was some legacy build code that I borrowed from one of my other repositories. It shouldn't be necessary.

**Comment by alerque** [comment]
@sursly and @micahbrich Unless somebody raises their arms and starts flailing frantically, this is going to land in `master` and a subsequent tagged release very soon. As far as I can tell everything is building beautifully and it's time to make this canonical.

**Comment by sursly** [comment]
Cool, looks/sounds good to me. Thanks for putting in a bunch of work on all these repos.

**Pull request merged**
